"""
This module retrieves relevant data from the database in response to function calls 
generated by the LLM, and supplies the retrieved information for use in the LLM's 
response generation stage.
"""

from typing import Any, Dict
from dotenv import load_dotenv

from src.utils.logger_config import setup_logger
from src.llm.llm_client import LlmClient
from src.database.neo4j_database import Neo4jDatabase
from src.agents.agent import create_agent

# Load environment variables
load_dotenv()

# Set up module-level logger
logger = setup_logger(__name__)


def retrieve_data(llm_client: LlmClient, query: str) -> Dict[str, Any]:
    """
    Uses the agent to invoke the appropriate database function 
    based on the input query, then returns the response.

    Args:
        llm_client (LlmClient): Initialized LLM client with database and prompt chains.
        query (str): Natural language question or command from user.

    Returns:
        Dict[str, Any]: Response generated by the agent or error information.
    """
    try:
        logger.debug(f"Asking agent to answer query: {query}")

        # Create the agent using the provided LLM client and database
        agent_executor = create_agent(
            llm_client=llm_client,
            database=llm_client.database
        )

        try:
            # Invoke the agent with the user query
            tool_output = agent_executor.invoke({"input": query})
            return tool_output

        except IndexError as ie:
            logger.error(f"Agent failed to retrieve data due to an IndexError: {ie}", exc_info=True)
            return {"error": "Failed to retrieve data due to an unexpected API response."}

    except Exception as e:
        logger.error(f"An unexpected error occurred: {e}", exc_info=True)
        raise e
