"""This module retrieves relevant data from the database in response 
to function calls generated by the LLM, and supplies the retrieved 
information for use in the LLM's response generation stage."""

import os
from dotenv import load_dotenv
from utils.logger_config import setup_logger

load_dotenv()

logger = setup_logger(__name__)

logger.debug("from the retriever.py")

